# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [9]:
print(np.zeros(10, dtype=int))

[0 0 0 0 0 0 0 0 0 0]


#### Create an array of 10 ones

In [10]:
print(np.ones(10, dtype=int))

[1 1 1 1 1 1 1 1 1 1]


#### Create an array of 10 fives

In [57]:
print(5*np.ones(10, dtype=int))
print(np.zeros(10, dtype=int)+5)

[5 5 5 5 5 5 5 5 5 5]
[5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50

In [12]:
print(np.arange(10,51, dtype=int))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [13]:
print(np.arange(10,51,2, dtype=int))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [58]:
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [60]:
print(np.eye(3, dtype = int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### Use NumPy to generate a random number between 0 and 1

In [22]:
print(np.random.rand(1))  # or just np.random.rand() works - default (0,1)

[0.38876285]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [61]:
print(np.random.normal(0,1,25).reshape((5,5)))
print(np.random.randn(25).reshape((5,5)))

[[-1.46667492 -0.77611789  0.87996898 -1.20986615  0.60956961]
 [ 1.253096   -0.36037497  0.5847408  -0.84404054  0.26535749]
 [ 0.65485537 -0.48699089  0.53685618  0.61951957 -2.32172998]
 [ 1.20282856 -1.59125574  0.2722645   1.17591832  1.40081928]
 [-0.16762625  0.50674243 -1.70850037 -1.4698137  -0.38133026]]
[[-1.62294607  1.11443589  0.68429585  0.746943   -0.79974891]
 [ 1.14895467 -0.33929473  0.92919289 -1.66669052 -0.38150409]
 [ 0.90549998  1.39424433 -1.53616981 -1.03892636 -1.49126684]
 [-1.13463525  1.09252679 -0.09368806  0.00394803 -0.73138844]
 [-1.54617843 -0.02184737 -1.19127138 -0.68417068 -1.75865206]]


#### Create the following matrix:

In [62]:
print(np.linspace(0.01,1,100).reshape((10,10)))
print(np.arange(1,101).reshape(10,10)/100)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]
[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.8

#### Create an array of 20 linearly spaced points between 0 and 1:

In [36]:
print(np.linspace(0,1,20).reshape((4,5)))

[[0.         0.05263158 0.10526316 0.15789474 0.21052632]
 [0.26315789 0.31578947 0.36842105 0.42105263 0.47368421]
 [0.52631579 0.57894737 0.63157895 0.68421053 0.73684211]
 [0.78947368 0.84210526 0.89473684 0.94736842 1.        ]]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [38]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [39]:
print(mat[2:,1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [40]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [63]:
print(mat[3,4])

20


In [43]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [65]:
print(mat[:3,1:2]) 
print(mat[:3,1].reshape((3,1))) # If you don't specify the rows perfectly it yields list

[[ 2]
 [ 7]
 [12]]
[[ 2]
 [ 7]
 [12]]


In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [66]:
print(mat[-1,:])
print(mat[4,:])

[21 22 23 24 25]
[21 22 23 24 25]


In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [67]:
print(mat[3:5,:])
print(mat[3:,:])

[[16 17 18 19 20]
 [21 22 23 24 25]]
[[16 17 18 19 20]
 [21 22 23 24 25]]


### Now do the following

#### Get the sum of all the values in mat

In [68]:
print(mat.sum())
print(np.sum(mat))

325
325


#### Get the standard deviation of the values in mat

In [69]:
print(mat.std())
print(np.std(mat))

7.211102550927978
7.211102550927978


#### Get the sum of all the columns in mat

In [71]:
print(mat.sum(axis=0))   # Click shift + Tab to see input - outputs of the function
print(np.sum(mat,axis=0))

[55 60 65 70 75]
[55 60 65 70 75]


# Great Job!